spring:
  application:
    name: tdra-ssir-backend

  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    serialization:
      fail-on-empty-beans: false

  messages:
    basename: messages
    encoding: UTF-8

server:
  port: 8080
  error:
    include-message: always

minio:
  endpoint: http://localhost:9100
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: ssir-documents

security:
  jwt:
    secret: dG5zLWNvbS1zc2lyLWVudGVycHJpc2Utc2VjdXJpdHktZmlsdGVyLWNoYWluLWtleS0yMDI2LXByb2Q=
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 604800000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha